name: nixos rebuild
run-name: nixos rebuild
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "nixos/**"
      - ".github/workflows/rebuild-nixos.yaml"

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        host: ["homelab-0"]
    name: Build
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: nixos-rebuild build --flake "github:thomvandevin/homelab?dir=nixos&rev=${{github.sha}}#$(hostname)"

  switch:
    strategy:
      max-parallel: 1
      matrix:
        host: ["homelab-0", "homelab-1", "homelab-2"]
    needs: [build]
    runs-on: self-hosted
    environment: live
    name: Switch
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: echo ${{ secrets.SU_PWD }} | sudo -S nixos-rebuild switch --flake "github:thomvandevin/homelab?dir=nixos&rev=${{github.sha}}#$(hostname)"
